# 配置网关
spring:
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedHeaders: "*"
            allowedOrigins: "*"
            allowCredentials: true
            allowedMethods: "*"
      routes:
        - id: user-service  服务名称
          uri: lb://user-service  #路径的服务名称，使用负载均衡lb
          predicates:
            - Path=/user/**  # 访问user路径转发用户服务
        - id: product-service
          uri: lb://product-service
          predicates:
            - Path=/product/**
        - id: static-service
          uri: lb://static-service
          predicates:
            - Path=/public/**
        - id: carousel-service
          uri: lb://carousel-service
          predicates:
            - Path=/carousel/**
        - id: category-service
          uri: lb://category-service
          predicates:
            - Path=/category/**
        - id: search-service
          uri: lb://search-service
          predicates:
            - Path=/search/**
        - id: collect-service
          uri: lb://collect-service
          predicates:
            - Path=/collect/**
        - id: cart-service
          uri: lb://cart-service
          predicates:
            - Path=/cart/**
        - id: order-service
          uri: lb://order-service
          predicates:
            - Path=/order/**
        - id: admin-service  # 后台管理服务
          uri: lb://admin-service
          predicates:
            - Path=/admin/**
        - id: history-service
          uri: lb://history-service
          predicates:
            - Path=/history/**